language: ruby
rvm:
- 2.1.4
before_install: wget --no-check-certificate https://dl.bintray.com/mitchellh/packer/packer_0.7.2_linux_amd64.zip
  && unzip -d packer packer_0.7.2_linux_amd64.zip
before_script: export PATH=$PATH:$PWD/packer
script: bundle exec thor packer:validate
notifications:
  slack:
    secure: ohPy5LBZD5NGfkkcLARb76330m8HtSDgNEAEljdkJ8NpCRaH0TFX/aVun8u6tOqdfXGH2wr/R+Aoghi0bbP+d+C5DOoIfa1nURPshkHF/2mZf2QuMrbQALPfv2l3FSlWuMfX9a8th3F1t/L3mj9qVKqYFWHlBOmHl6QrSpOKXFY=
